### ISSUE TITLE
Add the connectivity matrix but need the pathLength

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/openchemlib-extended#12]
@andcastillo 

In order to get the Paths the former code use something like:
 floydWarshall(this.getAdjacencyMatrix()) 

I don't know if this floydWarshall was implemented in mljs but I could not find it. What I did is to create the connectivity matrix (getConnectivityMatrix) and I have prepared the getAllPaths function. What is missing is this floydWarshall that from a matrix returns a matrix.

Please could you had it in the mljs organisation and publish it on npm ?

Here is the current function:

https://github.com/cheminfo-js/openchemlib-extended/blob/b6ecf8a56fe7eb979e28a0b1ec981f526702f9ae/src/extend/getAllPaths.js

and it yields something like

```
[ { fromDiaID: 'eMBBYRZA~d`xUP',
    toDiaID: 'gC`HALiKT@RHDRj@',
    fromAtoms: [ 0, 0, 0, 2, 2, 2 ],
    toAtoms: [ 3, 4, 5, 8, 9, 10 ],
    fromLabel: 'C',
    toLabel: 'H',
    pathLength: 1 },
  { fromDiaID: 'eMBBYchGzRCaU@',
    toDiaID: 'gC`HALiMT@RHDRj@',
    fromAtoms: [ 1, 1 ],
    toAtoms: [ 6, 7 ],
    fromLabel: 'C',
    toLabel: 'H',
    pathLength: 1 } ]
```

Maybe the fromAtoms and toAtoms should be unique ?

**Comment by andcastillo** [comment]
@lpatiny can you add the function to the help and fix the eslint of the getAllPaths.js file?

```
### getAllPaths(options)

Returns an array containing all-pairs shortest paths from a connectivity matrix using the FloydWarshall algorithm.
options:
* fromLabel: filter the pairs that start from this specific atom (default: '')
* toLabel: filter the pairs that end at this specific atom (default: '')
* minLength: min path length to report (default: 1)
* maxLength: max path length to report (default: 4)
```

**Comment by andcastillo** [comment]
@lpatiny  you can close this.
