### ISSUE TITLE
PSA logP logS should have only 2 digits by default

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/openchemlib-extended#7]
When calculated properties I think by default there should be only 2 digits. There could still be an option if we really wanted to get all the digits.

For mw: 2 digits
For exact mass: 4 digits

**Comment by targos** [comment]
May I ask why?

**Comment by lpatiny** [comment]
If you calculate the error on the prediction it really does not make sense to provide all the digits. So in the result you are always expected to round the number before presenting it to the user. Would be easier to do it by default.

**Comment by targos** [comment]
this is a display thing. It doesn't belong here
