### ISSUE TITLE
Failing test on travis

### ISSUE THREAD

**Issue by lpatiny** [cheminfo-js/openchemlib-extended#9]
The test are working smoothly on the terminal but not on travis and I don't know why. Both should not have the window to make test test.

https://travis-ci.org/cheminfo-js/openchemlib-extended/builds/141315115

**Comment by targos** [comment]
it should fail on your end when you update dependencies

**Comment by lpatiny** [comment]
Closed by 6f2a574808207b64e3bbee4bd58baf276bd22105
